//! Characterization test generator — produces test skeletons from extraction data.
//!
//! Analyzes event handlers, data flows, state transitions, and navigation paths
//! from graph edges and generates test classes covering each extraction edge.

use engram_graph::{Edge, EdgeKind, GraphStore, Node};
use serde::Serialize;
use std::collections::{BTreeMap, HashSet};
use std::fmt::Write;
use std::sync::Arc;

/// Result of characterization test generation.
#[derive(Debug, Clone, Serialize)]
pub struct CharacterizationTestResult {
    /// Generated test class code.
    pub test_code: String,
    /// Coverage map: which extraction edges each test covers.
    pub coverage_map: Vec<TestCoverageEntry>,
    /// Test framework used.
    pub framework: String,
    /// Number of tests generated.
    pub test_count: usize,
    /// Warnings during generation.
    pub warnings: Vec<String>,
}

/// Coverage entry mapping a test to the edges it covers.
#[derive(Debug, Clone, Serialize)]
pub struct TestCoverageEntry {
    pub test_name: String,
    pub category: TestCategory,
    pub covered_edges: Vec<String>,
    pub covered_nodes: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum TestCategory {
    EventHandler,
    DataFlow,
    StateTransition,
    Navigation,
    ApiContract,
}

/// Test framework selection.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TestFramework {
    NUnit,
    XUnit,
    MSTest,
}

impl TestFramework {
    pub fn from_str(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "xunit" | "x-unit" => Self::XUnit,
            "mstest" | "ms-test" | "ms_test" => Self::MSTest,
            _ => Self::NUnit,
        }
    }

    fn test_attribute(&self) -> &'static str {
        match self {
            Self::NUnit => "[Test]",
            Self::XUnit => "[Fact]",
            Self::MSTest => "[TestMethod]",
        }
    }

    fn fixture_attribute(&self) -> &'static str {
        match self {
            Self::NUnit => "[TestFixture]",
            Self::XUnit => "",
            Self::MSTest => "[TestClass]",
        }
    }

    fn setup_attribute(&self) -> &'static str {
        match self {
            Self::NUnit => "[SetUp]",
            Self::XUnit => "",
            Self::MSTest => "[TestInitialize]",
        }
    }

    fn assert_eq(&self, left: &str, right: &str) -> String {
        match self {
            Self::NUnit => format!("Assert.That({left}, Is.EqualTo({right}));"),
            Self::XUnit => format!("Assert.Equal({right}, {left});"),
            Self::MSTest => format!("Assert.AreEqual({right}, {left});"),
        }
    }

    fn assert_not_null(&self, expr: &str) -> String {
        match self {
            Self::NUnit => format!("Assert.That({expr}, Is.Not.Null);"),
            Self::XUnit => format!("Assert.NotNull({expr});"),
            Self::MSTest => format!("Assert.IsNotNull({expr});"),
        }
    }

    fn usings(&self) -> &'static str {
        match self {
            Self::NUnit => "using NUnit.Framework;\nusing Moq;",
            Self::XUnit => "using Xunit;\nusing Moq;",
            Self::MSTest => "using Microsoft.VisualStudio.TestTools.UnitTesting;\nusing Moq;",
        }
    }
}

/// Context collected from graph for test generation.
#[allow(dead_code)]
struct TestGenContext {
    functions: Vec<Node>,
    sql_edges: Vec<Edge>,
    reads_state: Vec<Edge>,
    writes_state: Vec<Edge>,
    reads_column: Vec<Edge>,
    queries_table: Vec<Edge>,
    parameter_bindings: Vec<Edge>,
    triggers_postback: Vec<Edge>,
    dependency_edges: Vec<Edge>,
    service_edges: Vec<Edge>,
    connection_strings: Vec<Node>,
}

// ─── Public API ───────────────────────────────────────────────────────────────

/// Generate characterization tests for a specific file.
pub fn generate_characterization_tests(
    graph: &Arc<GraphStore>,
    project_id: &str,
    file_path: &str,
    framework_str: &str,
) -> anyhow::Result<CharacterizationTestResult> {
    let fw = TestFramework::from_str(framework_str);
    let ctx = collect_test_context(graph, project_id, file_path)?;
    let mut warnings = Vec::new();

    let page_name = extract_page_name(file_path);
    let class_name = format!("{page_name}_CharacterizationTests");

    let mut code = String::with_capacity(8192);
    let mut coverage = Vec::new();
    let mut test_count = 0;

    // Header
    let _ = writeln!(code, "{}", fw.usings());
    let _ = writeln!(code, "using System.Threading.Tasks;");
    let _ = writeln!(code);
    let _ = writeln!(
        code,
        "// Auto-generated characterization tests for {file_path}"
    );
    let _ = writeln!(
        code,
        "// Generated by Engram-MCP — capture current behavior before migration"
    );
    let _ = writeln!(code);

    if !fw.fixture_attribute().is_empty() {
        let _ = writeln!(code, "{}", fw.fixture_attribute());
    }
    let _ = writeln!(code, "public class {class_name}");
    let _ = writeln!(code, "{{");

    // Fields
    let _ = writeln!(code, "    private MockHttpSession _session;");
    if !ctx.sql_edges.is_empty() {
        let _ = writeln!(code, "    private Mock<IDbConnection> _mockDb;");
    }
    let _ = writeln!(code);

    // Setup
    if !fw.setup_attribute().is_empty() {
        let _ = writeln!(code, "    {}", fw.setup_attribute());
    }
    let setup_name = if fw == TestFramework::XUnit {
        format!("    public {class_name}()")
    } else {
        "    public void Setup()".into()
    };
    let _ = writeln!(code, "{setup_name}");
    let _ = writeln!(code, "    {{");
    let _ = writeln!(code, "        _session = new MockHttpSession();");
    if !ctx.sql_edges.is_empty() {
        let _ = writeln!(code, "        _mockDb = new Mock<IDbConnection>();");
    }
    let _ = writeln!(code, "    }}");

    // 1. Event handler tests
    for func in &ctx.functions {
        let fname = &func.name;
        if !is_event_handler(fname) {
            continue;
        }

        let test_name = format!(
            "{fname}_Should_Execute_Expected_Behavior"
        );
        let _ = writeln!(code);
        let _ = writeln!(code, "    {}", fw.test_attribute());
        let _ = writeln!(code, "    public void {test_name}()");
        let _ = writeln!(code, "    {{");

        // Arrange: mock state reads
        let handler_reads: Vec<&Edge> = ctx
            .reads_state
            .iter()
            .filter(|e| e.source_id.contains(fname))
            .collect();
        let handler_writes: Vec<&Edge> = ctx
            .writes_state
            .iter()
            .filter(|e| e.source_id.contains(fname))
            .collect();
        let handler_sql: Vec<&Edge> = ctx
            .sql_edges
            .iter()
            .filter(|e| e.source_id.contains(fname))
            .collect();

        let _ = writeln!(code, "        // Arrange");
        for read_edge in &handler_reads {
            let key = read_edge
                .target_id
                .strip_prefix("state:")
                .unwrap_or(&read_edge.target_id);
            let _ = writeln!(
                code,
                "        _session[\"{key}\"] = \"TEST_VALUE\"; // Read by {fname}"
            );
        }

        // Act
        let _ = writeln!(code);
        let _ = writeln!(code, "        // Act");
        let _ = writeln!(
            code,
            "        // TODO: invoke {fname} on the page instance"
        );
        let _ = writeln!(
            code,
            "        // var page = CreatePage(); page.{fname}(sender, EventArgs.Empty);"
        );

        // Assert: check state writes
        let _ = writeln!(code);
        let _ = writeln!(code, "        // Assert");
        for write_edge in &handler_writes {
            let key = write_edge
                .target_id
                .strip_prefix("state:")
                .unwrap_or(&write_edge.target_id);
            let _ = writeln!(
                code,
                "        // {}",
                fw.assert_not_null(&format!("_session[\"{key}\"]"))
            );
        }
        for sql in &handler_sql {
            let target = &sql.target_id;
            let _ = writeln!(
                code,
                "        // Verify SQL executed: {target}"
            );
        }
        if handler_writes.is_empty() && handler_sql.is_empty() {
            let _ = writeln!(
                code,
                "        // TODO: capture expected output from legacy app run"
            );
        }

        let _ = writeln!(code, "    }}");

        let mut covered_edges = Vec::new();
        for e in &handler_reads {
            covered_edges.push(format!(
                "ReadsState:{} → {}",
                e.source_id, e.target_id
            ));
        }
        for e in &handler_writes {
            covered_edges.push(format!(
                "WritesState:{} → {}",
                e.source_id, e.target_id
            ));
        }
        for e in &handler_sql {
            covered_edges.push(format!(
                "SqlCalls:{} → {}",
                e.source_id, e.target_id
            ));
        }

        coverage.push(TestCoverageEntry {
            test_name: test_name.clone(),
            category: TestCategory::EventHandler,
            covered_edges,
            covered_nodes: vec![func.node_id.clone()],
        });
        test_count += 1;
    }

    // 2. Data flow tests — one per SQL query
    let mut sql_test_idx = 0;
    for sql_edge in &ctx.sql_edges {
        let sql_text = sql_edge
            .metadata
            .as_ref()
            .and_then(|m| m.get("sql").or_else(|| m.get("command_text")))
            .and_then(|v| v.as_str())
            .unwrap_or("unknown");

        let test_name = format!("DataFlow_{sql_test_idx}_Should_Return_Expected_Columns");
        let _ = writeln!(code);
        let _ = writeln!(code, "    {}", fw.test_attribute());
        let _ = writeln!(code, "    public void {test_name}()");
        let _ = writeln!(code, "    {{");
        let _ = writeln!(code, "        // Arrange");
        let _ = writeln!(code, "        // SQL: {sql_text}");

        // Parameter bindings for this query
        let params: Vec<&Edge> = ctx
            .parameter_bindings
            .iter()
            .filter(|e| e.source_id == sql_edge.source_id)
            .collect();
        for param in &params {
            let _ = writeln!(
                code,
                "        // Parameter: {}",
                param.target_id
            );
        }

        // Expected columns
        let columns: Vec<&Edge> = ctx
            .reads_column
            .iter()
            .filter(|e| e.source_id == sql_edge.source_id)
            .collect();

        let _ = writeln!(code);
        let _ = writeln!(code, "        // Act");
        let _ = writeln!(
            code,
            "        // TODO: execute query and capture result"
        );
        let _ = writeln!(code);
        let _ = writeln!(code, "        // Assert — expected columns:");
        for col in &columns {
            let col_name = col
                .target_id
                .strip_prefix("col:")
                .unwrap_or(&col.target_id);
            let _ = writeln!(
                code,
                "        // - {col_name}"
            );
        }
        if columns.is_empty() {
            let _ = writeln!(
                code,
                "        // TODO: determine expected columns from legacy app"
            );
        }

        let _ = writeln!(code, "    }}");

        coverage.push(TestCoverageEntry {
            test_name,
            category: TestCategory::DataFlow,
            covered_edges: vec![format!(
                "SqlCalls:{} → {}",
                sql_edge.source_id, sql_edge.target_id
            )],
            covered_nodes: vec![],
        });
        test_count += 1;
        sql_test_idx += 1;
    }

    // 3. State transition tests — per state key
    let state_keys = collect_unique_state_keys(&ctx.reads_state, &ctx.writes_state);
    for (key, readers, writers) in &state_keys {
        let safe_key = key.replace(['[', ']', '"', '\''], "");
        let test_name = format!(
            "State_{safe_key}_Should_Be_Consistent"
        );
        let _ = writeln!(code);
        let _ = writeln!(code, "    {}", fw.test_attribute());
        let _ = writeln!(code, "    public void {test_name}()");
        let _ = writeln!(code, "    {{");
        let _ = writeln!(code, "        // State key: {key}");
        let _ = writeln!(
            code,
            "        // Writers ({} locations):",
            writers.len()
        );
        for w in writers {
            let _ = writeln!(code, "        //   - {w}");
        }
        let _ = writeln!(
            code,
            "        // Readers ({} locations):",
            readers.len()
        );
        for r in readers {
            let _ = writeln!(code, "        //   - {r}");
        }
        let _ = writeln!(code);
        let _ = writeln!(code, "        // Arrange");
        let _ = writeln!(
            code,
            "        _session[\"{safe_key}\"] = \"EXPECTED_VALUE\";"
        );
        let _ = writeln!(code);
        let _ = writeln!(code, "        // Act & Assert");
        let _ = writeln!(
            code,
            "        // TODO: verify write at each writer location, then verify read returns same value"
        );
        let _ = writeln!(code, "    }}");

        coverage.push(TestCoverageEntry {
            test_name,
            category: TestCategory::StateTransition,
            covered_edges: readers
                .iter()
                .map(|r| format!("ReadsState:{r} → {key}"))
                .chain(writers.iter().map(|w| format!("WritesState:{w} → {key}")))
                .collect(),
            covered_nodes: vec![],
        });
        test_count += 1;
    }

    // 4. Navigation tests — from dependency edges (Response.Redirect / Server.Transfer)
    for dep in &ctx.dependency_edges {
        let target = &dep.target_id;
        let source = &dep.source_id;
        let test_name = format!(
            "Navigation_Should_Redirect_To_{}",
            target
                .replace('/', "_")
                .replace('.', "_")
                .replace('\\', "_")
        );
        let _ = writeln!(code);
        let _ = writeln!(code, "    {}", fw.test_attribute());
        let _ = writeln!(code, "    public void {test_name}()");
        let _ = writeln!(code, "    {{");
        let _ = writeln!(code, "        // Source: {source}");
        let _ = writeln!(code, "        // Target: {target}");
        let _ = writeln!(code);
        let _ = writeln!(code, "        // Arrange");
        let _ = writeln!(
            code,
            "        // TODO: set up conditions for this navigation path"
        );
        let _ = writeln!(code);
        let _ = writeln!(code, "        // Act");
        let _ = writeln!(
            code,
            "        // TODO: trigger the action that causes navigation"
        );
        let _ = writeln!(code);
        let _ = writeln!(code, "        // Assert");
        let _ = writeln!(
            code,
            "        // Verify redirect to: {target}"
        );
        let _ = writeln!(code, "    }}");

        coverage.push(TestCoverageEntry {
            test_name,
            category: TestCategory::Navigation,
            covered_edges: vec![format!(
                "Dependency:{source} → {target}"
            )],
            covered_nodes: vec![],
        });
        test_count += 1;
    }

    // 5. API contract tests — for service endpoints
    for svc_edge in &ctx.service_edges {
        let endpoint = &svc_edge.target_id;
        let safe_name = endpoint
            .replace('/', "_")
            .replace('.', "_")
            .replace(':', "_");
        let test_name = format!("Contract_{safe_name}_Returns_Expected_Schema");

        let _ = writeln!(code);
        let _ = writeln!(code, "    {}", fw.test_attribute());
        let _ = writeln!(code, "    public async Task {test_name}()");
        let _ = writeln!(code, "    {{");
        let _ = writeln!(
            code,
            "        // Service endpoint: {endpoint}"
        );
        let _ = writeln!(code, "        var client = new HttpClient();");
        let _ = writeln!(code);
        let _ = writeln!(code, "        // Act");
        let _ = writeln!(
            code,
            "        var response = await client.GetAsync(\"{endpoint}\");"
        );
        let _ = writeln!(code);
        let _ = writeln!(code, "        // Assert");
        let _ = writeln!(
            code,
            "        {}",
            fw.assert_eq("(int)response.StatusCode", "200")
        );
        let _ = writeln!(
            code,
            "        {}",
            fw.assert_not_null("await response.Content.ReadAsStringAsync()")
        );
        let _ = writeln!(code, "    }}");

        coverage.push(TestCoverageEntry {
            test_name,
            category: TestCategory::ApiContract,
            covered_edges: vec![format!(
                "Service:{} → {}",
                svc_edge.source_id, endpoint
            )],
            covered_nodes: vec![],
        });
        test_count += 1;
    }

    let _ = writeln!(code, "}}");

    if test_count == 0 {
        warnings.push(
            "No extraction data found for test generation — ensure the file has been indexed"
                .into(),
        );
    }

    Ok(CharacterizationTestResult {
        test_code: code,
        coverage_map: coverage,
        framework: format!("{framework_str}"),
        test_count,
        warnings,
    })
}

// ─── Internals ────────────────────────────────────────────────────────────────

fn collect_test_context(
    graph: &Arc<GraphStore>,
    project_id: &str,
    file_path: &str,
) -> anyhow::Result<TestGenContext> {
    let all_fns = graph.query_nodes(project_id, Some("function"), None, None, 5000)?;
    let functions: Vec<Node> = all_fns
        .into_iter()
        .filter(|n| n.file_path.as_str() == file_path)
        .collect();

    let filter = |edges: Vec<Edge>| -> Vec<Edge> {
        edges
            .into_iter()
            .filter(|e| {
                e.source_id.contains(file_path)
                    || e.metadata
                        .as_ref()
                        .and_then(|m| m.get("file_path"))
                        .and_then(|v| v.as_str())
                        .is_some_and(|fp| fp == file_path)
            })
            .collect()
    };

    let sql_edges = filter(graph.list_edges_by_kind(project_id, EdgeKind::SqlCalls, 10_000)?);
    let reads_state = filter(graph.list_edges_by_kind(project_id, EdgeKind::ReadsState, 10_000)?);
    let writes_state = filter(graph.list_edges_by_kind(project_id, EdgeKind::WritesState, 10_000)?);
    let reads_column = filter(graph.list_edges_by_kind(project_id, EdgeKind::ReadsColumn, 10_000)?);
    let queries_table =
        filter(graph.list_edges_by_kind(project_id, EdgeKind::QueriesTable, 10_000)?);
    let parameter_bindings =
        filter(graph.list_edges_by_kind(project_id, EdgeKind::ParameterBinding, 10_000)?);
    let triggers_postback =
        filter(graph.list_edges_by_kind(project_id, EdgeKind::TriggersPostback, 10_000)?);
    let dependency_edges =
        filter(graph.list_edges_by_kind(project_id, EdgeKind::Dependency, 10_000)?);

    let mut service_edges = Vec::new();
    for kind in [
        EdgeKind::ExposesWebService,
        EdgeKind::ExposesHttpHandler,
        EdgeKind::ExposesWcfService,
    ] {
        service_edges.extend(filter(
            graph.list_edges_by_kind(project_id, kind, 1000)?,
        ));
    }

    let all_conns = graph.query_nodes(project_id, Some("connection_string"), None, None, 500)?;
    let connection_strings: Vec<Node> = all_conns
        .into_iter()
        .filter(|n| n.file_path.as_str() == file_path)
        .collect();

    Ok(TestGenContext {
        functions,
        sql_edges,
        reads_state,
        writes_state,
        reads_column,
        queries_table,
        parameter_bindings,
        triggers_postback,
        dependency_edges,
        service_edges,
        connection_strings,
    })
}

fn is_event_handler(name: &str) -> bool {
    name.contains("_Click")
        || name.contains("_Command")
        || name.contains("_Changed")
        || name.contains("_SelectedIndexChanged")
        || name.contains("_Load")
        || name.contains("_Init")
        || name.contains("_PreRender")
        || name.contains("_DataBound")
        || name.contains("_RowCommand")
        || name.contains("_RowDataBound")
        || name.contains("_ItemCommand")
}

fn extract_page_name(file_path: &str) -> String {
    file_path
        .replace('\\', "/")
        .rsplit('/')
        .next()
        .unwrap_or(file_path)
        .replace(".aspx.cs", "")
        .replace(".aspx.vb", "")
        .replace(".aspx", "")
        .replace(".ascx.cs", "")
        .replace(".ascx.vb", "")
        .replace(".ascx", "")
        .replace(".cs", "")
        .replace(".vb", "")
}

fn collect_unique_state_keys(
    reads: &[Edge],
    writes: &[Edge],
) -> Vec<(String, Vec<String>, Vec<String>)> {
    let mut key_readers: BTreeMap<String, HashSet<String>> = BTreeMap::new();
    let mut key_writers: BTreeMap<String, HashSet<String>> = BTreeMap::new();

    for e in reads {
        let key = e
            .target_id
            .strip_prefix("state:")
            .unwrap_or(&e.target_id)
            .to_string();
        key_readers
            .entry(key)
            .or_default()
            .insert(e.source_id.clone());
    }
    for e in writes {
        let key = e
            .target_id
            .strip_prefix("state:")
            .unwrap_or(&e.target_id)
            .to_string();
        key_writers
            .entry(key)
            .or_default()
            .insert(e.source_id.clone());
    }

    let mut all_keys: HashSet<String> = HashSet::new();
    all_keys.extend(key_readers.keys().cloned());
    all_keys.extend(key_writers.keys().cloned());

    let mut result: Vec<(String, Vec<String>, Vec<String>)> = all_keys
        .into_iter()
        .map(|k| {
            let r = key_readers
                .get(&k)
                .map(|s| s.iter().cloned().collect::<Vec<_>>())
                .unwrap_or_default();
            let w = key_writers
                .get(&k)
                .map(|s| s.iter().cloned().collect::<Vec<_>>())
                .unwrap_or_default();
            (k, r, w)
        })
        .collect();
    result.sort_by(|a, b| a.0.cmp(&b.0));
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_framework_attributes() {
        let nunit = TestFramework::NUnit;
        assert_eq!(nunit.test_attribute(), "[Test]");
        assert_eq!(nunit.fixture_attribute(), "[TestFixture]");

        let xunit = TestFramework::XUnit;
        assert_eq!(xunit.test_attribute(), "[Fact]");
        assert!(xunit.fixture_attribute().is_empty());

        let mstest = TestFramework::MSTest;
        assert_eq!(mstest.test_attribute(), "[TestMethod]");
        assert_eq!(mstest.fixture_attribute(), "[TestClass]");
    }

    #[test]
    fn test_framework_from_str() {
        assert_eq!(TestFramework::from_str("nunit"), TestFramework::NUnit);
        assert_eq!(TestFramework::from_str("xunit"), TestFramework::XUnit);
        assert_eq!(TestFramework::from_str("mstest"), TestFramework::MSTest);
        assert_eq!(TestFramework::from_str("unknown"), TestFramework::NUnit);
    }

    #[test]
    fn test_framework_assert_eq() {
        let nunit = TestFramework::NUnit;
        assert!(nunit
            .assert_eq("a", "b")
            .contains("Assert.That(a, Is.EqualTo(b))"));

        let xunit = TestFramework::XUnit;
        assert!(xunit.assert_eq("a", "b").contains("Assert.Equal(b, a)"));

        let mstest = TestFramework::MSTest;
        assert!(mstest
            .assert_eq("a", "b")
            .contains("Assert.AreEqual(b, a)"));
    }

    #[test]
    fn is_event_handler_detection() {
        assert!(is_event_handler("Button_Click"));
        assert!(is_event_handler("GridView_RowCommand"));
        assert!(is_event_handler("DropDown_SelectedIndexChanged"));
        assert!(is_event_handler("Page_Load"));
        assert!(!is_event_handler("LoadData"));
        assert!(!is_event_handler("ProcessOrder"));
    }

    #[test]
    fn extract_page_name_variants() {
        assert_eq!(extract_page_name("Orders.aspx.cs"), "Orders");
        assert_eq!(extract_page_name("Admin/Users.aspx.vb"), "Users");
        assert_eq!(extract_page_name("Controls/Header.ascx"), "Header");
    }

    #[test]
    fn collect_state_keys_groups() {
        let reads = vec![
            Edge {
                source_id: "fn:A".into(),
                target_id: "state:UserId".into(),
                namespace: "t".into(),
                language: "cs".into(),
                edge_kind: EdgeKind::ReadsState,
                weight: 1,
                generation: 1,
                metadata: None,
                updated_at_ms: 0,
            },
            Edge {
                source_id: "fn:B".into(),
                target_id: "state:UserId".into(),
                namespace: "t".into(),
                language: "cs".into(),
                edge_kind: EdgeKind::ReadsState,
                weight: 1,
                generation: 1,
                metadata: None,
                updated_at_ms: 0,
            },
        ];
        let writes = vec![Edge {
            source_id: "fn:C".into(),
            target_id: "state:UserId".into(),
            namespace: "t".into(),
            language: "cs".into(),
            edge_kind: EdgeKind::WritesState,
            weight: 1,
            generation: 1,
            metadata: None,
            updated_at_ms: 0,
        }];

        let keys = collect_unique_state_keys(&reads, &writes);
        assert_eq!(keys.len(), 1);
        assert_eq!(keys[0].0, "UserId");
        assert_eq!(keys[0].1.len(), 2); // 2 readers
        assert_eq!(keys[0].2.len(), 1); // 1 writer
    }

    #[test]
    fn test_category_serialization() {
        let json = serde_json::to_string(&TestCategory::EventHandler).unwrap_or_default();
        assert!(json.contains("event_handler"));
    }
}
