//! Markdown rendering for the full-project migration report.
//!
//! `render_markdown` is a thin orchestrator that calls every
//! `render_section_*` function in the order they appeared in the
//! original monolithic implementation.

#![allow(clippy::too_many_arguments)]

use std::collections::BTreeMap;

use super::model::*;
use super::super::auth_config_service::AuthConfigMap;
use super::super::db_strategy_service::FileDataAccessProfile;
use super::super::dossier_service::MigrationDossier;
use super::super::migration_order_service::MigrationOrderPlan;
use super::super::state_migration_service::StateMigrationReport;

pub(super) mod sections;

#[allow(clippy::too_many_arguments)]
pub(super) fn render_markdown(
    project_id: &str,
    target_stack: &str,
    generated_at: &str,
    order: &MigrationOrderPlan,
    state: &StateMigrationReport,
    auth: &AuthConfigMap,
    data_access: &[FileDataAccessProfile],
    dossiers: &[MigrationDossier],
    cross: &CrossCuttingSummary,
    wave_lookup: &BTreeMap<String, u32>,
    js: &JsAnalysisSummary,
    gis: &GisAnalysisSummary,
    webconfig: &WebConfigInventory,
    endpoints: &ServiceEndpointSummary,
    global: &GlobalAsaxSummary,
    anti: &AntiPatternSummary,
    asp: &ClassicAspSummary,
    rpt: &ReportSummary,
    method_inv: &BTreeMap<String, PageMethodInventory>,
    third_party: &ThirdPartyControlSummary,
    dep_inv: &DependencyInventory,
    cache_inv: &CachingInventory,
    url_routing: &UrlRoutingInventory,
    vb_trans: &VbTranslationReport,
    multi_tenant: &MultiTenancyReport,
    email: &EmailPatternReport,
    bg_jobs: &BackgroundJobReport,
    sp_cat: &StoredProcedureCatalog,
    inherit: &InheritanceChainReport,
    cfg_transforms: &ConfigTransformReport,
    master_regions: &MasterPageRegionMap,
    res_inv: &ResourceInventory,
    vb_traps: &engram_index::vb_translation_traps::VbTranslationTrapReport,
    jquery_inv: &engram_index::jquery_inventory::JQueryInventory,
    cross_traces: &CrossLayerTraceSummary,
    biz_logic: &crate::services::business_logic_service::ProjectBusinessLogicReport,
    db_intel: &crate::services::database_intelligence_service::DatabaseIntelligence,
    session_wf: &crate::services::session_workflow_service::SessionWorkflowReport,
) -> String {
    let mut md = String::with_capacity(180_000);
    sections::summary::render_section_prelude(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::summary::render_section_header(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::summary::render_section_executive_summary(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::summary::render_section_project_dependencies(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::translation::render_section_language_translation_analysis(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::auth::render_section_authentication_authorization(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::auth::render_section_multi_tenancy_analysis(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::lifecycle::render_section_global_asax(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::config::render_section_web_config_inventory(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::config::render_section_url_routing_rewriting(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::lifecycle::render_section_state_management(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::lifecycle::render_section_caching_strategy(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::data::render_section_data_access_patterns(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::data::render_section_code_behind_method_inventory(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::endpoints::render_section_service_endpoints(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::endpoints::render_section_javascript_typescript_client_side_dependencies(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::endpoints::render_section_gis_spatial_analysis(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::legacy::render_section_third_party_control_libraries(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::legacy::render_section_design_anti_patterns(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::operations::render_section_email_notifications(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::operations::render_section_background_processing(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::legacy::render_section_classic_asp(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::legacy::render_section_reports(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::finale::render_section_migration_wave_plan(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::finale::render_section_cross_cutting_concerns(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::finale::render_section_page_by_page_dossiers(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::data::render_section_stored_procedure_catalog(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::data::render_section_inheritance_chain_report(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::config::render_section_config_transforms(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::operations::render_section_master_page_region_map(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::operations::render_section_resource_file_inventory(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::config::render_section_binding_redirects(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::translation::render_section_vb_translation_traps(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::endpoints::render_section_jquery_ecosystem_inventory(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::data::render_section_cross_layer_data_flow_chains(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::data::render_section_inherited_effects(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::finale::render_section_risk_assessment(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::finale::render_section_business_logic_summary(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::finale::render_section_database_intelligence(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::finale::render_section_session_workflows(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    sections::finale::render_section_migration_intelligence_confidence_dashboard(&mut md, project_id, target_stack, generated_at, order, state, auth, data_access, dossiers, cross, wave_lookup, js, gis, webconfig, endpoints, global, anti, asp, rpt, method_inv, third_party, dep_inv, cache_inv, url_routing, vb_trans, multi_tenant, email, bg_jobs, sp_cat, inherit, cfg_transforms, master_regions, res_inv, vb_traps, jquery_inv, cross_traces, biz_logic, db_intel, session_wf);
    md
}
